import type {Metadata} from 'next'
import {Josefin_Sans} from 'next/font/google'
import './globals.css'
import Navigation from './components/Navigation'

const josefinSans = Josefin_Sans({subsets: ['latin']})

export const metadata: Metadata = {
	title: 'Appolly',
	description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
	return (
		<html
			lang="en"
			className="bg-black"
		>
			<body className={`${josefinSans.className}`}>
				<header className="bg-hero-image bg-cover bg-center bg-no-repeat h-screen">
					<Navigation />
				</header>
				{children}
			</body>
		</html>
	)
}
